name: BC Check
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  bc_check:
    name: Backwards Compatibility Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Check for BC breaks"
        run: vendor/bin/roave-backward-compatibility-check
